version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    ignore:
      # chai is esmodule only.
      - dependency-name: "chai"
        versions: [">=5.0.0"]
      # sinon-chai 4.x+ supports chai 5.x+.
      - dependency-name: "sinon-chai"
        versions: [">=4.0.0"]
      # nyc is Node18+ only starting on nyc@16.x.
      - dependency-name: "nyc"
        versions: [">=16.0.0"]
      # we ignore TS as a part of quarterly dependency updates.
      - dependency-name: "typescript"
      # node-gyp now depends on python 3.10, we install 3.6 in our dockerfile
      - dependency-name: "node-gyp"
      
    groups:
      development-dependencies:
        dependency-type: "development"
        applies-to: version-updates
        update-types:
        - "minor"
        - "patch"