on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write
  id-token: write

name: release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: googleapis/release-please-action@v4

      - if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'

      - if: ${{ steps.release.outputs.release_created }}
        run: npm install -g npm@latest
        shell: bash

      - if: ${{ steps.release.outputs.release_created }}
        run: npm clean-install
        shell: bash

      - if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - if: ${{ steps.release.outputs.release_created }}
        run: npm publish --workspaces
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
